name: Release Cordova Plugin (GitHub)

on:
  push:
    branches:
      - test/automated-release
  workflow_dispatch:

permissions:
    contents: write

jobs:   
  release:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN_GITHUB }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25
      - name: Install dependencies root
        shell: bash
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN_GITHUB }}
        run: npx semantic-release
