name: Release Cordova Plugin (GitHub)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write   # Needed to create PR


jobs:   
  release:
    if: github.ref_name == 'main' || github.ref_name == 'release'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN_GITHUB }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Install dependencies
        run: npm ci
      
      - name: Read package.json version before release
        id: before
        run: |
          PACKAGE_VERSION_BEFORE=$(node -p 'require("./package.json").version')
          echo "PACKAGE_VERSION_BEFORE=$PACKAGE_VERSION_BEFORE" >> $GITHUB_ENV
          echo "PACKAGE_VERSION_BEFORE: $PACKAGE_VERSION_BEFORE"

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN_GITHUB }}
        run: npx semantic-release
      
      - name: Read package.json version after release
        id: after
        run: |
          PACKAGE_VERSION_AFTER=$(node -p 'require("./package.json").version')
          echo "PACKAGE_VERSION_AFTER=$PACKAGE_VERSION_AFTER" >> $GITHUB_ENV
          echo "PACKAGE_VERSION_AFTER: $PACKAGE_VERSION_AFTER"

      - name: Create PR to main
        if: github.ref_name == 'release' && env.PACKAGE_VERSION_BEFORE != env.PACKAGE_VERSION_AFTER
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN_GITHUB }}
        run: |
          git checkout -b release-pr-${GITHUB_RUN_NUMBER}
          git push origin HEAD
          gh pr create \
            --title "Release $PACKAGE_VERSION_AFTER" \
            --body "$(cat <<'EOF'
            # **Do NOT squash nor rebase**, use regular merge commit, in order to keep commit hashes and tags
            ## Automated Release PR

            **Plugin Version:** $PACKAGE_VERSION_AFTER  
            **GitHub Run ID:** $GITHUB_RUN_NUMBER  

            _This PR was automatically created by the release workflow._
            EOF
            )" \
            --base main \
            --head release-pr-${GITHUB_RUN_NUMBER} \
            --repo $GITHUB_REPOSITORY